### ISSUE TITLE
Synchronize ADS126X measurement and Arduino data read

### ISSUE THREAD

**Issue by AlbiBone** [Molorius/ADS126X#10]
How can I synchronize the samples coming from ADS126X chip (at `setRate(uint8_t rate)` frequency) and the Arduino reading using `adc.readADC1(pos_pin,neg_pin)` ? 
It is very important that no samples are lost during the comunication for problems of different synchronization. Maybe using the interupt technique?

**Comment by Molorius** [comment]
You can use the DRDY pin to verify when the adc has made a new reading. You can also put the adc in pulse conversion (one shot conversion) mode, so it will only start a new voltage reading when you tell it to.
