### ISSUE TITLE
ads1262 pin label assignation from library

### ISSUE THREAD

**Issue by cotixtof** [Molorius/ADS126X#15]
Hi, how to change the DRDY, START, PWDN and MISO, MOSI, SCLK pins' assignation used by the library? Chris

**Comment by Molorius** [comment]
Hello.

DRDY is a pin on the ADC to know when data is ready, if you need this you should read it with a spare gpio. It is not controlled by this library. 

PWDN is also optional on the ADC and not controlled by this library. Read the datasheet to see if this should be held high or low. 

MISO, MOSI, and SCLK are all SPI pins. Arduino's SPI implementation has hardcoded pins and varies based on the board. If you have a different SPI implementation then you'll need to add another board similar to https://github.com/Molorius/ADS126X/blob/0be0e1fbea6e71a74f156f2f152eb1961c44da8b/src/boards/arduino.cpp.
