### ISSUE TITLE
Biais voltage 

### ISSUE THREAD

**Issue by cotixtof** [Molorius/ADS126X#16]
Hi, 
We are using an ads1262 powered by +5V ; GND and AGND connected together, AVDD and DVDD as well.
When connecting AIN0 and AIN1 to AGND, the digital output is +30mV, when connecting AIN0 to AGND and AIN1 to a voltage of 1650mV, the digital output is 1640mV.
What do we do wrong?
chris

**Comment by Molorius** [comment]
Hi Chris,

See 9.4.9.8 of the datasheet for offset and full-scale calibration. This library has functions to run the automatic calibration (see "Calibration Functions" of the readme) but not yet to read or set the values from the registers.

**Comment by cotixtof** [comment]
Thanks!
