### ISSUE TITLE
IDAC1, IDAC2 and getting VREF from AIN0 to AIN5

### ISSUE THREAD

**Issue by q-bird** [Molorius/ADS126X#4]
Hi there,

1. Are there any functions to set IDAC1 and IDAC2 with the value from 50uA-3000uA as mentioned in the datasheet? IDAC is useful to measure RTDs or NTC...
2. With RTD sensor we need to read the REF voltage from AIN0-AIN1 or AIN2-AIN3 or AIN4-AIN5, not the internal ref, so is there any function to do it?
3. Is there any function to set ADC pin as single-ended input instead of diff-pair? And we also have AINCOM pin which can be the 11st ADC pin, how to measure from this pin?

Thank you!

**Comment by Molorius** [comment]
1. This has not been implemented yet, but should not take very long. 
2. There is a pull request for this, see #3. 
3. You can set the negative side to ADS126X_ANALOG for the negative analog power supply monitor or ADS126X_DIGITAL for the negative digital power supply monitor to get single-ended input, depending on your use-case. AINCOM pin is set by ADS126X_AINCOM. All of this is documented in [the README](https://github.com/Molorius/ADS126X#int32_t-readadc1uint8_t-pos_pinuint8_t-neg_pin).

**Comment by q-bird** [comment]
@Molorius Thanks for your quick answers!

BTW, you mean you are going to implement the IDAC feature?
>     1. This has not been implemented yet, but should not take very long.

We can say that we can use this `setReference` function now right?
And will you merge it after you put the description for this function into the README?
>     2. There is a pull request for this, see #3.

Thanks again!

**Comment by Molorius** [comment]
I can implement the IDAC feature, but it will have to be in the next week or so. 

You can use the setReference function right now if you use that person's fork. I will merge and add documentation to it when I add the IDAC feature, unless they document it sooner than that.

**Comment by q-bird** [comment]
Hi @Molorius 
Any updates for IDAC?

**Comment by Molorius** [comment]
IDAC functionality was added in 0be0e1f, but I don't have a solid way of testing it. Could you test to make sure it was implemented correctly?

**Comment by q-bird** [comment]
@Molorius Thank you I will test it and get back to you soon

**Comment by q-bird** [comment]
Hi @Molorius 

I jst tested IDAC functionality:
- IDAC1 and IDAC2 are working independently with each other (assigned to two different pins parallel)
- I can measure the value from 50uA to 3000uA using an Ampere meter! 
In the other words, this functionality is working well :)

Thanks so much for your update!

**Comment by Molorius** [comment]
Fantastic, I will close this then.
