### ISSUE TITLE
Measurment with rispect to the supply voltage

### ISSUE THREAD

**Issue by AlbiBone** [Molorius/ADS126X#8]
Hi guys,

I would like to measure the output voltage of my load cell. For this reason I attach on analog pins 1 and 2 the output voltages of the bridge. I use the example sketch of this library and if I understood well, the ADS1262 subtract the voltages calculating the voltage difference of the bridge.
The problem is here. Since the supply voltage of the loadcell can slightly vary sligly, that affect the output voltage of the loadcell causing an measurment error.

My question is the following: is it possible to measure with ADS1262 both input and output voltages of my loadcel and "normalize" the output with rispect the input fluctuation?
Or something similar that avoid the measuremnt problem caused by the noise and ripple of supply voltage used to feed the loadcell.

Regards,
A

**Comment by jgueldenstein** [comment]
What power supply are you using?

I would highly recommend to decrease the noise on your supply voltage if you try to read load cells. A low noise LDO that powers the analog part of the ADS1262 and provides voltage to the load cells should suffice.

**Comment by Molorius** [comment]
I also suggest using a stable supply voltage to your load cell. 

But you can use the load cell power supply as a reference voltage. Check page 41 of the datasheet for more details. This is implemented with the `setReference` function.

**Comment by AlbiBone** [comment]
Dear @jgueldenstein , I am a new user of Arduino & libraries (for work and personal usage purposes). For this reason I am trying to learn from the expert like you.

About power supply I use the voltage coming from of my Arduino Due board (a 3.3V board), as described here:
- for ADS1262 digial (DVDD) = 3.3 V (from Arduino Due board),
- for ADS1262 analog (AVDD) = 5V (from Arduino Due board),
- loadcell power supply = 5V (from Arduino Due board).

Obviously the Arduino is used also to read the data coming from ADS1262 using SPI protocol.
However since the Arduino voltage supply could be affected by noise, the output of the loadcell is affected to noise (proportional to the input disturbance). Therefore I would like to reduce this effect in some way. Maybe using `setReference ` as suggested by @Molorius .

**Comment by jgueldenstein** [comment]
Are you using the 5V pin from the Arduino to power the ADS1262 and loadcell?
As far as I can tell the 5V coming from the Arduino Due comes from the 5V USB bus. There are a lot of devices on that bus that can cause noise. It can theoretically vary from 4.4V to 5.25V.

For my purpose I use a low dropout regulator (TS2937CW-50 to be specific) to regulate the voltage coming from a 4 cell LiPo battery (14.8-16.8V) to 5V.
You need some kind of power supply that is capable of producing at least 5.5V or more.

**Comment by AlbiBone** [comment]
Yes, @jgueldenstein , my idea was to using the 5V pin from the Arduino to power the ADS1262 and loadcell, and to reduce the noise I would like to make a ratiometric measurment,
Anyhow according to your suggestion, I am looking for a more stable power supply as you suggested (and I will make a ratiometric measurment using `setReference`).
Thanks for your hints!

**Comment by Molorius** [comment]
I will assume you fixed your problem, reopen if you still need help.
