### ISSUE TITLE
Timing of multi-channel measurement

### ISSUE THREAD

**Issue by AlbiBone** [Molorius/ADS126X#9]
Hi everyone,
since I would like to measure at high speed more than one analog signal, I am afraid about the synchronization of the analog channels.
Are the signals acquired simultaneously? If not, how can I overcome the problem of the voltages measured in times sligtly different for each channel?

Regards,
A

**Comment by Molorius** [comment]
Are you positive you NEED simultaneous measurements? Both the ADS1262 and ADS1263 can take up to 38400 samples per second, which should be sufficient for most applications. The ADS1263 also has a 24 bit ADC, but this is intended for "background measurements". 

If you absolutely need simultaneous measurements, you may need to use a different ADC. I found many options by searching for "adc simultaneous sampling" online.

**Comment by AlbiBone** [comment]
My question is referred to the case of measurement of many signals that are not measured at the same time. More in detail, the measurment is sliglty affected by timing errors.
Anyhow, as you suggested @Molorius , using a high data rate (e.g. 38,4 kHz) can help to reduce this effect.
The last question: is it possible to determine the time lag between the to signals?

**Comment by Molorius** [comment]
I am not positive, a careful reading of the datasheet is necessary to determine that.
